stages:
    - build
    - dev-deploy
    - deploy

build:
    stage: build
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    artifacts:
        paths:
            - dist/
    script:
        - pnpm i
        - pnpm build

dev-deploy-chromium-light:
    stage: dev-deploy
    except:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - git checkout main
        - docker buildx create --use
        - ./scripts/docker_dev.sh chromium-light

dev-deploy-chromium:
    stage: dev-deploy
    except:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - git checkout main
        - docker buildx create --use
        - ./scripts/docker_dev.sh chromium

dev-deploy-firefox:
    stage: dev-deploy
    except:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - git checkout main
        - docker buildx create --use
        - ./scripts/docker_dev.sh firefox

dev-deploy-webkit:
    stage: dev-deploy
    except:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - git checkout main
        - docker buildx create --use
        - ./scripts/docker_dev.sh webkit

dev-deploy-chrome:
    stage: dev-deploy
    except:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - git checkout main
        - docker buildx create --use
        - ./scripts/docker_dev.sh chrome

dev-deploy-msedge:
    stage: dev-deploy
    except:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - git checkout main
        - docker buildx create --use
        - ./scripts/docker_dev.sh msedge

dev-deploy-all:
    stage: dev-deploy
    except:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - git checkout main
        - docker buildx create --use
        - ./scripts/docker_dev.sh all

deploy-chromium-light:
    stage: deploy
    only:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker buildx create --use
        - ./scripts/docker_release.sh chromium-light

deploy-chromium:
    stage: deploy
    only:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker buildx create --use
        - ./scripts/docker_release.sh chromium

deploy-firefox:
    stage: deploy
    only:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker buildx create --use
        - ./scripts/docker_release.sh firefox

deploy-webkit:
    stage: deploy
    only:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker buildx create --use
        - ./scripts/docker_release.sh webkit

deploy-chrome:
    stage: deploy
    only:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker buildx create --use
        - ./scripts/docker_release.sh chrome

deploy-msedge:
    stage: deploy
    only:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker buildx create --use
        - ./scripts/docker_release.sh msedge

deploy-all:
    stage: deploy
    only:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    services:
        - docker:dind
    dependencies:
        - build
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker buildx create --use
        - ./scripts/docker_release.sh all

deploy-npm:
    stage: deploy
    only:
        - tags
    image: ghcr.io/jacoblincool/gitlab-ci-container:latest
    dependencies:
        - build
    before_script:
        - npm config set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
    script:
        - pnpm i && pnpm build
        - pnpm publish --verbose --access public --no-git-checks
