name: Publish

on:
    push:
        branches:
            - main
        paths-ignore:
            - "**.md"
    workflow_dispatch:

jobs:
    publish_action:
        name: Publish Action
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache PNPM Modules
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: latest
                  run_install: true

            - name: Build Action
              run: pnpm build:action

            - name: Commit
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  publish_dir: "./dist/action"
                  user_name: "JacobLinCool"
                  user_email: "jacoblincool@users.noreply.github.com"
                  publish_branch: "action"

    publish_binary:
        name: Publish Binary
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache PNPM Modules
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: latest
                  run_install: true

            - name: Build Binary
              run: pnpm build:binary

            - name: Commit
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  publish_dir: "./dist/binary"
                  user_name: "JacobLinCool"
                  user_email: "jacoblincool@users.noreply.github.com"
                  publish_branch: "binary"

    publish_docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v3

            - name: Install PNPM
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: latest
                  run_install: true

            - name: Build Package
              run: pnpm build:package

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Image and Push
              run: |
                  pnpm build:package
                  pnpm build:docker

    build_docs:
        name: Build Docs
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache PNPM Modules
              uses: actions/cache@v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: latest
                  run_install: true

            - name: Build Docs
              run: pnpm docs

            - name: Commit
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
                  publish_dir: "./web"
                  user_name: "JacobLinCool"
                  user_email: "jacoblincool@users.noreply.github.com"
                  publish_branch: "gh-pages"
